"""trivia_questions.py — the starter Trail Trivia question bank.

A curated set of JCI-themed multiple-choice questions across four categories:
jci_history, leadership, global, and ottawa. Each question has exactly one
correct answer letter ('a'|'b'|'c'|'d'). Seeded via
``Repository.seed_trivia_questions`` (idempotent — skips duplicates by text).

These are deliberately general/educational; adjust or expand freely. The daily
puzzle draws 3 at random (seeded by date) so a larger bank keeps things fresh.
"""

TRIVIA_QUESTIONS = [
    # -- JCI history & foundations -----------------------------------------
    {
        "question": "What does 'JCI' stand for?",
        "option_a": "Junior Chamber International",
        "option_b": "Joint Community Initiative",
        "option_c": "Junior Council International",
        "option_d": "Justice & Community Institute",
        "correct": "a",
        "category": "jci_history",
        "difficulty": "easy",
    },
    {
        "question": "In what year was JCI (as the Junior Chamber movement) founded by Henry Giessenbier?",
        "option_a": "1901",
        "option_b": "1915",
        "option_c": "1920",
        "option_d": "1945",
        "correct": "c",
        "category": "jci_history",
        "difficulty": "medium",
    },
    {
        "question": "JCI is a global network of young active citizens between which ages?",
        "option_a": "16 to 30",
        "option_b": "18 to 40",
        "option_c": "21 to 45",
        "option_d": "25 to 50",
        "correct": "b",
        "category": "jci_history",
        "difficulty": "easy",
    },
    {
        "question": "What is the name of JCI's flagship recognition for outstanding young people?",
        "option_a": "The Global Leaders Award",
        "option_b": "TOYP (Ten Outstanding Young Persons)",
        "option_c": "The Impact Prize",
        "option_d": "The Citizenship Medal",
        "correct": "b",
        "category": "jci_history",
        "difficulty": "medium",
    },
    # -- JCI Creed / values -------------------------------------------------
    {
        "question": "The JCI Creed begins: 'We believe: That faith in ___ gives meaning and purpose to human life.'",
        "option_a": "each other",
        "option_b": "God",
        "option_c": "the future",
        "option_d": "community",
        "correct": "b",
        "category": "jci_history",
        "difficulty": "hard",
    },
    {
        "question": "According to the JCI Creed, 'economic justice can best be won by ___ men through ___ enterprise.'",
        "option_a": "free / free",
        "option_b": "young / bold",
        "option_c": "all / shared",
        "option_d": "active / social",
        "correct": "a",
        "category": "jci_history",
        "difficulty": "hard",
    },
    # -- Leadership skills --------------------------------------------------
    {
        "question": "Which leadership style focuses on inspiring and motivating followers toward a shared vision?",
        "option_a": "Transactional",
        "option_b": "Autocratic",
        "option_c": "Transformational",
        "option_d": "Laissez-faire",
        "correct": "c",
        "category": "leadership",
        "difficulty": "medium",
    },
    {
        "question": "In a SWOT analysis, what does the 'O' stand for?",
        "option_a": "Objectives",
        "option_b": "Opportunities",
        "option_c": "Outcomes",
        "option_d": "Operations",
        "correct": "b",
        "category": "leadership",
        "difficulty": "easy",
    },
    {
        "question": "Which of these is a hallmark of active listening?",
        "option_a": "Planning your reply while they speak",
        "option_b": "Interrupting to save time",
        "option_c": "Paraphrasing to confirm understanding",
        "option_d": "Checking your phone",
        "correct": "c",
        "category": "leadership",
        "difficulty": "easy",
    },
    {
        "question": "A SMART goal is Specific, Measurable, Achievable, Relevant, and what?",
        "option_a": "Tactical",
        "option_b": "Time-bound",
        "option_c": "Transparent",
        "option_d": "Team-based",
        "correct": "b",
        "category": "leadership",
        "difficulty": "easy",
    },
    {
        "question": "What is 'delegation' in a leadership context?",
        "option_a": "Doing all critical work yourself",
        "option_b": "Assigning responsibility and authority to others",
        "option_c": "Avoiding difficult decisions",
        "option_d": "Reporting to a higher authority",
        "correct": "b",
        "category": "leadership",
        "difficulty": "easy",
    },
    # -- Global initiatives / UN SDGs --------------------------------------
    {
        "question": "JCI is a partner of the United Nations. How many Sustainable Development Goals (SDGs) are there?",
        "option_a": "8",
        "option_b": "12",
        "option_c": "17",
        "option_d": "21",
        "correct": "c",
        "category": "global",
        "difficulty": "medium",
    },
    {
        "question": "Which UN SDG focuses on 'Quality Education'?",
        "option_a": "SDG 3",
        "option_b": "SDG 4",
        "option_c": "SDG 8",
        "option_d": "SDG 11",
        "correct": "b",
        "category": "global",
        "difficulty": "medium",
    },
    {
        "question": "The JCI annual global gathering of members from around the world is called the:",
        "option_a": "Global Summit",
        "option_b": "World Congress",
        "option_c": "International Forum",
        "option_d": "Annual Assembly",
        "correct": "b",
        "category": "global",
        "difficulty": "easy",
    },
    {
        "question": "Roughly how many countries and territories does JCI operate in?",
        "option_a": "About 30",
        "option_b": "About 60",
        "option_c": "Over 100",
        "option_d": "Exactly 195",
        "correct": "c",
        "category": "global",
        "difficulty": "medium",
    },
    # -- Ottawa / Canada ----------------------------------------------------
    {
        "question": "In which Canadian province or territory is the city of Ottawa located?",
        "option_a": "Quebec",
        "option_b": "Ontario",
        "option_c": "Manitoba",
        "option_d": "Nova Scotia",
        "correct": "b",
        "category": "ottawa",
        "difficulty": "easy",
    },
    {
        "question": "Ottawa is the capital city of which country?",
        "option_a": "Canada",
        "option_b": "Australia",
        "option_c": "New Zealand",
        "option_d": "United States",
        "correct": "a",
        "category": "ottawa",
        "difficulty": "easy",
    },
    {
        "question": "JCI's 'One Year to Lead' philosophy refers to what?",
        "option_a": "A one-year membership trial",
        "option_b": "Annual leadership terms that rotate each year",
        "option_c": "A one-year community project",
        "option_d": "A leadership certification program",
        "correct": "b",
        "category": "leadership",
        "difficulty": "medium",
    },
    {
        "question": "What famous canal running through Ottawa becomes the world's largest skating rink in winter?",
        "option_a": "Erie Canal",
        "option_b": "Welland Canal",
        "option_c": "Rideau Canal",
        "option_d": "Trent-Severn Waterway",
        "correct": "c",
        "category": "ottawa",
        "difficulty": "medium",
    },
]
