import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  getRecommendation,
  generateRecommendation,
  markRecommendationSent,
  ApiError,
} from '../api.js';

/**
 * WellingtonAdviceCard — the "Wellington the Wise" AI retention-recommendation
 * card shown for an At_Risk_Member (task 19.4).
 *
 * Requirements covered:
 *   8.1  — surface the intervention-eligible affordance for an At_Risk_Member:
 *          this card is the entry point to request an AI_Retention_Intervention
 *          and view its Retention_Recommendation.
 *   8.9  — when a Retention_Recommendation exists, display it together with an
 *          action to copy the Outreach_Template and an action to mark the
 *          recommendation as sent.
 *   8.10 — marking a recommendation as sent records a UTC timestamp; the card
 *          reflects the sent status/timestamp on the member's record.
 *   8.11 — display a fallback-mode indicator identifying the recommendation as
 *          template-generated when mode === "template"; a subtle AI-generated
 *          note when mode === "llm".
 *
 * API shapes (backend api/routes_recommendations.py, tasks 19.1/19.2):
 *   getRecommendation(memberId)  -> stored recommendation, or a 404 ApiError
 *     with code "recommendation_not_found" when none is stored yet:
 *       { outcome: "recommendation", mode: "llm" | "template",
 *         diagnosis, events: [{ title, event_date, url, reason }],
 *         outreach_template, created_at, sent, sent_at }
 *   generateRecommendation(memberId) -> one of:
 *       { outcome: "recommendation", mode, diagnosis, events, outreach_template }
 *       | { outcome: "no_events", message }
 *       | { outcome: "error", reason, message }
 *     A 409 ApiError (code/reason "not_eligible") is thrown for a member that
 *     is not currently at risk (Req 8.2, surfaced here as guidance).
 *   markRecommendationSent(memberId) -> { member_id, sent, sent_at }
 *
 * The card is authored to be mounted where a member is selected; it takes the
 * member's id (and optional display name) as props.
 */

// The intervention can take up to ~30s end-to-end (web search + synthesis).
const GENERATE_HINT =
  'Wellington searches for relevant local events and drafts outreach — this can take up to 30 seconds.';

/**
 * Format an ISO timestamp readably for the sent-status line (Req 8.10). Falls
 * back to the raw value when it cannot be parsed.
 */
function formatTimestamp(iso) {
  if (!iso || typeof iso !== 'string') {
    return '';
  }
  const parsed = new Date(iso);
  if (Number.isNaN(parsed.getTime())) {
    return iso;
  }
  try {
    return parsed.toLocaleString(undefined, {
      dateStyle: 'medium',
      timeStyle: 'short',
    });
  } catch {
    return parsed.toISOString();
  }
}

/** Format an event date (ISO YYYY-MM-DD) readably; defensive on bad input. */
function formatEventDate(value) {
  if (!value || typeof value !== 'string') {
    return '';
  }
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return value;
  }
  try {
    return parsed.toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  } catch {
    return value;
  }
}

/**
 * Fallback-mode / provenance indicator (Req 8.11). Mirrors the SourceIndicator
 * pattern in MemberQuery.jsx: the template case is called out prominently, the
 * LLM case gets a subtle note.
 */
function ModeIndicator({ mode }) {
  if (mode === 'template') {
    return (
      <p
        className="wellington-source wellington-source--fallback"
        title="The AI was unavailable; this recommendation was assembled from a fixed template."
      >
        ⚙️ Template-generated (AI was unavailable)
      </p>
    );
  }
  if (mode === 'llm') {
    return (
      <p
        className="wellington-source wellington-source--llm"
        title="Synthesized by Wellington the Wise."
      >
        ✨ AI-generated by Wellington
      </p>
    );
  }
  return null;
}

/** A single Recommended_Event entry (Req 8.9 recommendation body). */
function RecommendedEvent({ event }) {
  const hasUrl = event && typeof event.url === 'string' && event.url;
  return (
    <li className="wellington-event">
      <div className="wellington-event-header">
        {hasUrl ? (
          <a
            className="wellington-event-title"
            href={event.url}
            target="_blank"
            rel="noopener noreferrer"
          >
            {event.title}
          </a>
        ) : (
          <span className="wellington-event-title">{event.title}</span>
        )}
        {event.event_date ? (
          <span className="wellington-event-date">
            {formatEventDate(event.event_date)}
          </span>
        ) : null}
      </div>
      {event.reason ? (
        <p className="wellington-event-reason">{event.reason}</p>
      ) : null}
    </li>
  );
}

export default function WellingtonAdviceCard({ memberId, memberName }) {
  // The current recommendation (from either a stored load or a fresh generate).
  const [recommendation, setRecommendation] = useState(null);
  // Non-recommendation generate outcomes: "no_events" | "error".
  const [outcomeState, setOutcomeState] = useState(null);
  // Sent status/timestamp tracked locally (Req 8.10).
  const [sent, setSent] = useState(false);
  const [sentAt, setSentAt] = useState(null);

  const [initialLoading, setInitialLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [marking, setMarking] = useState(false);
  const [loadError, setLoadError] = useState(null);
  const [copied, setCopied] = useState(false);

  const copyTimerRef = useRef(null);

  const applyRecommendation = useCallback((rec, { markSent = false } = {}) => {
    setRecommendation(rec);
    setOutcomeState(null);
    // Stored recommendations carry sent/sent_at; freshly generated ones don't.
    setSent(markSent ? true : Boolean(rec && rec.sent));
    setSentAt(rec && rec.sent_at ? rec.sent_at : null);
  }, []);

  // On mount, load any previously stored recommendation. A 404 with code
  // "recommendation_not_found" is NOT an error — it just means "none yet".
  useEffect(() => {
    let cancelled = false;
    setInitialLoading(true);
    setLoadError(null);
    setRecommendation(null);
    setOutcomeState(null);
    setSent(false);
    setSentAt(null);

    (async () => {
      try {
        const stored = await getRecommendation(memberId);
        if (cancelled) return;
        applyRecommendation(stored);
      } catch (err) {
        if (cancelled) return;
        if (
          err instanceof ApiError &&
          (err.status === 404 || err.code === 'recommendation_not_found')
        ) {
          // No stored recommendation yet — show the generate/empty state.
          setRecommendation(null);
        } else if (err instanceof ApiError) {
          setLoadError(err.message || 'Could not load the recommendation.');
        } else {
          setLoadError('An unexpected error occurred while loading advice.');
        }
      } finally {
        if (!cancelled) setInitialLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [memberId, applyRecommendation]);

  // Clear the copy-confirmation timer on unmount.
  useEffect(() => {
    return () => {
      if (copyTimerRef.current) {
        clearTimeout(copyTimerRef.current);
      }
    };
  }, []);

  const handleGenerate = useCallback(async () => {
    setGenerating(true);
    setLoadError(null);
    setOutcomeState(null);
    setCopied(false);
    try {
      const result = await generateRecommendation(memberId);
      if (result && result.outcome === 'recommendation') {
        // A freshly generated recommendation is not yet marked as sent.
        applyRecommendation(result);
      } else if (result && result.outcome === 'no_events') {
        setRecommendation(null);
        setOutcomeState({ kind: 'no_events', message: result.message });
      } else if (result && result.outcome === 'error') {
        setRecommendation(null);
        setOutcomeState({
          kind: 'error',
          reason: result.reason,
          message: result.message,
        });
      } else {
        setRecommendation(null);
        setOutcomeState({
          kind: 'error',
          message: 'Received an unrecognized response. Please try again.',
        });
      }
    } catch (err) {
      setRecommendation(null);
      if (
        err instanceof ApiError &&
        (err.status === 409 || err.code === 'not_eligible')
      ) {
        // Req 8.2 — surfaced as guidance for a non-at-risk member.
        setOutcomeState({ kind: 'error', reason: 'not_eligible' });
      } else if (err instanceof ApiError) {
        setOutcomeState({
          kind: 'error',
          message: err.message || 'The recommendation could not be generated.',
        });
      } else {
        setOutcomeState({
          kind: 'error',
          message: 'An unexpected error occurred while generating advice.',
        });
      }
    } finally {
      setGenerating(false);
    }
  }, [memberId, applyRecommendation]);

  const handleCopy = useCallback(async () => {
    const template = recommendation ? recommendation.outreach_template : '';
    if (!template) return;
    // Guard for clipboard API absence (e.g. insecure context / older browsers).
    if (
      typeof navigator === 'undefined' ||
      !navigator.clipboard ||
      typeof navigator.clipboard.writeText !== 'function'
    ) {
      return;
    }
    try {
      await navigator.clipboard.writeText(template);
      setCopied(true);
      if (copyTimerRef.current) {
        clearTimeout(copyTimerRef.current);
      }
      copyTimerRef.current = setTimeout(() => setCopied(false), 2000);
    } catch {
      // Silently ignore — the textarea below still lets the admin copy manually.
    }
  }, [recommendation]);

  const handleMarkSent = useCallback(async () => {
    setMarking(true);
    try {
      const result = await markRecommendationSent(memberId);
      setSent(true);
      setSentAt(result && result.sent_at ? result.sent_at : new Date().toISOString());
    } catch (err) {
      if (err instanceof ApiError) {
        setLoadError(err.message || 'Could not mark the recommendation as sent.');
      } else {
        setLoadError('An unexpected error occurred while marking as sent.');
      }
    } finally {
      setMarking(false);
    }
  }, [memberId]);

  const clipboardAvailable =
    typeof navigator !== 'undefined' &&
    navigator.clipboard &&
    typeof navigator.clipboard.writeText === 'function';

  const hasRecommendation =
    recommendation && recommendation.outcome === 'recommendation';
  const events = hasRecommendation && Array.isArray(recommendation.events)
    ? recommendation.events
    : [];

  return (
    <section className="wellington-card" aria-label="Wellington the Wise retention advice">
      <header className="wellington-header">
        <h2 className="wellington-title">🦉 Wellington the Wise</h2>
        <p className="wellington-subtitle">
          Retention advice{memberName ? ` for ${memberName}` : ''}
        </p>
      </header>

      {/* Load error (anything other than "none stored yet"). */}
      {loadError ? (
        <div className="wellington-error" role="alert">
          <p>⚠️ {loadError}</p>
        </div>
      ) : null}

      {/* Initial load of any stored recommendation. */}
      {initialLoading ? (
        <div className="wellington-loading" aria-busy="true">
          <p>Loading advice…</p>
        </div>
      ) : null}

      {/* Generate / regenerate action. */}
      {!initialLoading ? (
        <div className="wellington-actions">
          <button
            type="button"
            className="wellington-btn wellington-btn--primary"
            onClick={handleGenerate}
            disabled={generating || marking}
          >
            {generating
              ? 'Consulting Wellington…'
              : hasRecommendation
                ? 'Regenerate advice'
                : 'Generate advice'}
          </button>
          <p className="wellington-hint">{GENERATE_HINT}</p>
        </div>
      ) : null}

      {/* Generating state. */}
      {generating ? (
        <div className="wellington-loading" aria-busy="true">
          <p>Consulting Wellington…</p>
        </div>
      ) : null}

      {/* Non-recommendation generate outcomes. */}
      {!generating && outcomeState && outcomeState.kind === 'no_events' ? (
        <div className="wellington-status" role="status">
          <p>
            {outcomeState.message ||
              'No upcoming local events were found for this member in the next 30 days.'}
          </p>
        </div>
      ) : null}

      {!generating && outcomeState && outcomeState.kind === 'error' ? (
        <div className="wellington-error" role="alert">
          {outcomeState.reason === 'not_eligible' ? (
            <p>
              This member is not currently at risk, so retention advice isn't
              available.
            </p>
          ) : (
            <p>
              ⚠️{' '}
              {outcomeState.message ||
                'The recommendation could not be generated. Please try again.'}
            </p>
          )}
        </div>
      ) : null}

      {/* The recommendation itself (Req 8.9), when present. */}
      {!generating && hasRecommendation ? (
        <div className="wellington-recommendation">
          {/* Fallback-mode / provenance indicator (Req 8.11). */}
          <ModeIndicator mode={recommendation.mode} />

          {/* Diagnosis. */}
          <div className="wellington-section">
            <h3 className="wellington-section-title">Diagnosis</h3>
            <p className="wellington-diagnosis">{recommendation.diagnosis}</p>
          </div>

          {/* Recommended events (1–3). */}
          <div className="wellington-section">
            <h3 className="wellington-section-title">Recommended events</h3>
            {events.length === 0 ? (
              <p className="wellington-empty">No recommended events.</p>
            ) : (
              <ul className="wellington-event-list">
                {events.map((event, idx) => (
                  <RecommendedEvent key={`${event.title}-${idx}`} event={event} />
                ))}
              </ul>
            )}
          </div>

          {/* Outreach template + copy action (Req 8.9). */}
          <div className="wellington-section">
            <h3 className="wellington-section-title">Outreach message</h3>
            <textarea
              className="wellington-outreach"
              readOnly
              rows={6}
              value={recommendation.outreach_template || ''}
              aria-label="Outreach message template"
            />
            <div className="wellington-outreach-actions">
              <button
                type="button"
                className="wellington-btn"
                onClick={handleCopy}
                disabled={!clipboardAvailable || !recommendation.outreach_template}
                title={
                  clipboardAvailable
                    ? 'Copy the outreach message to the clipboard'
                    : 'Clipboard is unavailable; select and copy the text manually'
                }
              >
                {copied ? '✓ Copied!' : 'Copy Outreach Message'}
              </button>
              {!clipboardAvailable ? (
                <span className="wellington-hint">
                  Clipboard unavailable — select the text above to copy manually.
                </span>
              ) : null}
            </div>
          </div>

          {/* Mark-as-sent action / sent status (Req 8.10). */}
          <div className="wellington-section wellington-sent">
            {sent ? (
              <p className="wellington-sent-status" role="status">
                ✓ Sent{sentAt ? ` on ${formatTimestamp(sentAt)}` : ''}
              </p>
            ) : (
              <button
                type="button"
                className="wellington-btn wellington-btn--primary"
                onClick={handleMarkSent}
                disabled={marking}
              >
                {marking ? 'Marking…' : 'Mark as Sent'}
              </button>
            )}
          </div>
        </div>
      ) : null}
    </section>
  );
}
